# coding: utf-8

"""
    RenderForm API

    Swagger documentation for RenderForm API

    The version of the OpenAPI document: 5d659ea_2024-04-19_14-21-33
    Contact: contact@renderform.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ChangePlaceholder(BaseModel):
    """
    ChangePlaceholder
    """ # noqa: E501
    component_id: Optional[StrictStr] = Field(default=None, alias="componentId")
    component_type: Optional[StrictStr] = Field(default=None, alias="componentType")
    type: Optional[StrictStr] = None
    key: Optional[StrictStr] = None
    var_property: Optional[StrictStr] = Field(default=None, alias="property")
    default_value: Optional[StrictStr] = Field(default=None, alias="defaultValue")
    __properties: ClassVar[List[str]] = ["componentId", "componentType", "type", "key", "property", "defaultValue"]

    @field_validator('component_type')
    def component_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['RECTANGLE', 'CIRCLE', 'TEXT', 'IMAGE', 'QR_CODE', 'CHART', 'SVG_GROUP', 'RATING', 'HTML', 'TEST_OBJECT']):
            raise ValueError("must be one of enum values ('RECTANGLE', 'CIRCLE', 'TEXT', 'IMAGE', 'QR_CODE', 'CHART', 'SVG_GROUP', 'RATING', 'HTML', 'TEST_OBJECT')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChangePlaceholder from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChangePlaceholder from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "componentId": obj.get("componentId"),
            "componentType": obj.get("componentType"),
            "type": obj.get("type"),
            "key": obj.get("key"),
            "property": obj.get("property"),
            "defaultValue": obj.get("defaultValue")
        })
        return _obj


