# coding: utf-8

"""
    RenderForm API

    Swagger documentation for RenderForm API

    The version of the OpenAPI document: 5d659ea_2024-04-19_14-21-33
    Contact: contact@renderform.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RenderRequest(BaseModel):
    """
    RenderRequest
    """ # noqa: E501
    template: StrictStr = Field(description="Template ID")
    data: Optional[Dict[str, Dict[str, Any]]] = Field(default=None, description="Data to be merged into the template")
    file_name: Optional[StrictStr] = Field(default=None, description="Name of the file to be returned", alias="fileName")
    webhook_url: Optional[StrictStr] = Field(default=None, description="Webhook URL to be called when the render is done", alias="webhookUrl")
    version: Optional[StrictStr] = Field(default=None, description="Cache key to be used for caching the rendered image")
    metadata: Optional[Dict[str, Dict[str, Any]]] = Field(default=None, description="Additional metadata to be passed to the webhook")
    batch_name: Optional[StrictStr] = Field(default=None, description="Batch name to be used for grouping renders", alias="batchName")
    __properties: ClassVar[List[str]] = ["template", "data", "fileName", "webhookUrl", "version", "metadata", "batchName"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RenderRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RenderRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "template": obj.get("template"),
            "data": obj.get("data"),
            "fileName": obj.get("fileName"),
            "webhookUrl": obj.get("webhookUrl"),
            "version": obj.get("version"),
            "metadata": obj.get("metadata"),
            "batchName": obj.get("batchName")
        })
        return _obj


