# coding: utf-8

"""
    RenderForm API

    Swagger documentation for RenderForm API

    The version of the OpenAPI document: 5d659ea_2024-04-19_14-21-33
    Contact: contact@renderform.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.render_api_api import RenderAPIApi


class TestRenderAPIApi(unittest.TestCase):
    """RenderAPIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RenderAPIApi()

    def tearDown(self) -> None:
        pass

    def test_render_v2(self) -> None:
        """Test case for render_v2

        """
        pass


if __name__ == '__main__':
    unittest.main()
