# coding: utf-8

"""
    RenderForm API

    Swagger documentation for RenderForm API

    The version of the OpenAPI document: 5d659ea_2024-04-19_14-21-33
    Contact: contact@renderform.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.render_request import RenderRequest

class TestRenderRequest(unittest.TestCase):
    """RenderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RenderRequest:
        """Test RenderRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RenderRequest`
        """
        model = RenderRequest()
        if include_optional:
            return RenderRequest(
                template = 'template_1234',
                data = {"my-text.text":"John"},
                file_name = 'my-file-name',
                webhook_url = 'https://my-webhook.com',
                version = 'my-cache-key',
                metadata = {"my-text.text":"John"},
                batch_name = 'my-batch-name'
            )
        else:
            return RenderRequest(
                template = 'template_1234',
        )
        """

    def testRenderRequest(self):
        """Test RenderRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
