# coding: utf-8

"""
    RenderForm API

    Swagger documentation for RenderForm API

    The version of the OpenAPI document: 5d659ea_2024-04-19_14-21-33
    Contact: contact@renderform.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_template_basics import GetTemplateBasics

class TestGetTemplateBasics(unittest.TestCase):
    """GetTemplateBasics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTemplateBasics:
        """Test GetTemplateBasics
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTemplateBasics`
        """
        model = GetTemplateBasics()
        if include_optional:
            return GetTemplateBasics(
                identifier = '',
                name = '',
                preview = '',
                scale_factor = 1.337,
                output_format = '',
                output_extension = '',
                quality = 56,
                width = 56,
                height = 56,
                created_by = '',
                editor = '',
                properties = [
                    openapi_client.models.change_placeholder.ChangePlaceholder(
                        component_id = '', 
                        component_type = 'RECTANGLE', 
                        type = '', 
                        key = '', 
                        property = '', 
                        default_value = '', )
                    ],
                fonts = [
                    openapi_client.models.font_item.FontItem(
                        original_name = '', 
                        family = '', 
                        variants = [
                            ''
                            ], 
                        default_variant = '', 
                        subsets = [
                            ''
                            ], 
                        category = '', 
                        source = 'GOOGLE', 
                        size = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return GetTemplateBasics(
        )
        """

    def testGetTemplateBasics(self):
        """Test GetTemplateBasics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
