# coding: utf-8

"""
    RenderForm API

    Swagger documentation for RenderForm API

    The version of the OpenAPI document: 5d659ea_2024-04-19_14-21-33
    Contact: contact@renderform.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.templates_api_api import TemplatesAPIApi


class TestTemplatesAPIApi(unittest.TestCase):
    """TemplatesAPIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TemplatesAPIApi()

    def tearDown(self) -> None:
        pass

    def test_get_my_template(self) -> None:
        """Test case for get_my_template

        """
        pass

    def test_get_my_templates(self) -> None:
        """Test case for get_my_templates

        """
        pass


if __name__ == '__main__':
    unittest.main()
