# coding: utf-8

"""
    RenderForm API

    Swagger documentation for RenderForm API

    The version of the OpenAPI document: 5d659ea_2024-04-19_14-21-33
    Contact: contact@renderform.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.my_template_entry_v2 import MyTemplateEntryV2

class TestMyTemplateEntryV2(unittest.TestCase):
    """MyTemplateEntryV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MyTemplateEntryV2:
        """Test MyTemplateEntryV2
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MyTemplateEntryV2`
        """
        model = MyTemplateEntryV2()
        if include_optional:
            return MyTemplateEntryV2(
                identifier = '',
                name = '',
                preview = '',
                scale_factor = 1.337,
                output_format = '',
                output_extension = '',
                quality = 56,
                is_shared = True,
                is_live_preview_shared = True,
                is_email_notification = True,
                email_notification = '',
                width = 56,
                height = 56,
                created_by = '',
                editor = ''
            )
        else:
            return MyTemplateEntryV2(
        )
        """

    def testMyTemplateEntryV2(self):
        """Test MyTemplateEntryV2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
