# coding: utf-8

"""
    RenderForm API

    Swagger documentation for RenderForm API

    The version of the OpenAPI document: 5d659ea_2024-04-19_14-21-33
    Contact: contact@renderform.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.fonts_api_api import FontsAPIApi


class TestFontsAPIApi(unittest.TestCase):
    """FontsAPIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FontsAPIApi()

    def tearDown(self) -> None:
        pass

    def test_get_all_fonts(self) -> None:
        """Test case for get_all_fonts

        """
        pass


if __name__ == '__main__':
    unittest.main()
