# coding: utf-8

"""
    RenderForm API

    Swagger documentation for RenderForm API

    The version of the OpenAPI document: 5d659ea_2024-04-19_14-21-33
    Contact: contact@renderform.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.screenshots_api_api import ScreenshotsAPIApi


class TestScreenshotsAPIApi(unittest.TestCase):
    """ScreenshotsAPIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScreenshotsAPIApi()

    def tearDown(self) -> None:
        pass

    def test_create_screenshot(self) -> None:
        """Test case for create_screenshot

        """
        pass


if __name__ == '__main__':
    unittest.main()
